/** Trust boundary for rich HTML generated by models, tools, and the application. */
export type RichContentSource = 'agent' | 'search' | 'skill' | 'trusted-ui';

export interface RichContentPolicyOptions {
    source?: RichContentSource;
    /** Exact local:// media URLs returned by a trusted tool in this chat message. */
    trustedLocalMediaUrls?: readonly string[];
}

const REMOVE_ELEMENT_TAGS = new Set([
    'SCRIPT', 'NOSCRIPT', 'OBJECT', 'EMBED', 'APPLET', 'BASE', 'META', 'LINK',
    'TEMPLATE', 'PORTAL', 'FRAME', 'FRAMESET', 'FOREIGNOBJECT', 'STYLE'
]);
const UNWRAP_TAGS = new Set(['FORM']);
const URL_ATTRIBUTES = new Set(['href', 'src', 'poster', 'cite', 'background', 'xlink:href']);
const DROP_ATTRIBUTES = new Set(['action', 'formaction', 'ping', 'http-equiv', 'nonce', 'integrity']);

// Broad visual allowlist: creative HTML remains a product capability while
// network- and code-bearing CSS constructs stay outside the main chat DOM.
const SAFE_STYLE_PROPERTIES = new Set([
    'align-items', 'align-content', 'align-self', 'animation', 'animation-delay',
    'animation-direction', 'animation-duration', 'animation-fill-mode',
    'animation-iteration-count', 'animation-name', 'animation-play-state',
    'animation-timing-function', 'aspect-ratio', 'backdrop-filter', 'background',
    'background-color', 'background-image', 'background-position', 'background-repeat',
    'background-size', 'border', 'border-bottom', 'border-bottom-color',
    'border-bottom-left-radius', 'border-bottom-right-radius', 'border-bottom-style',
    'border-bottom-width', 'border-color', 'border-left', 'border-left-color',
    'border-left-style', 'border-left-width', 'border-radius', 'border-right',
    'border-right-color', 'border-right-style', 'border-right-width', 'border-style',
    'border-top', 'border-top-color', 'border-top-left-radius',
    'border-top-right-radius', 'border-top-style', 'border-top-width', 'border-width',
    'box-shadow', 'box-sizing', 'caption-side', 'clear', 'color', 'column-count',
    'column-gap', 'cursor', 'direction', 'display', 'filter', 'flex', 'flex-basis',
    'flex-direction', 'flex-flow', 'flex-grow', 'flex-shrink', 'flex-wrap', 'float',
    'font', 'font-family', 'font-size', 'font-style', 'font-variant', 'font-weight',
    'gap', 'grid', 'grid-area', 'grid-auto-columns', 'grid-auto-flow',
    'grid-auto-rows', 'grid-column', 'grid-column-end', 'grid-column-start',
    'grid-row', 'grid-row-end', 'grid-row-start', 'grid-template',
    'grid-template-areas', 'grid-template-columns', 'grid-template-rows', 'height',
    'hyphens', 'justify-content', 'justify-items', 'justify-self', 'letter-spacing',
    'line-height', 'list-style', 'list-style-position', 'list-style-type', 'margin',
    'margin-bottom', 'margin-left', 'margin-right', 'margin-top', 'max-height',
    'max-width', 'min-height', 'min-width', 'object-fit', 'object-position', 'opacity',
    'order', 'outline', 'overflow', 'overflow-wrap', 'overflow-x', 'overflow-y',
    'padding', 'padding-bottom', 'padding-left', 'padding-right', 'padding-top',
    'perspective', 'place-content', 'place-items', 'place-self', 'pointer-events',
    'position', 'rotate', 'row-gap', 'scale', 'table-layout', 'text-align',
    'text-decoration', 'text-decoration-color', 'text-decoration-line',
    'text-decoration-style', 'text-indent', 'text-overflow', 'text-shadow',
    'text-transform', 'transform', 'transform-origin', 'transition',
    'transition-delay', 'transition-duration', 'transition-property',
    'transition-timing-function', 'translate', 'unicode-bidi', 'vertical-align',
    'visibility', 'white-space', 'width', 'word-break', 'word-spacing', 'word-wrap'
]);
const DANGEROUS_CSS = /(?:expression\s*\(|url\s*\(|@import|javascript:|vbscript:|data\s*:|behavior\s*:|-moz-binding|\\)/i;
const DANGEROUS_SVG_CSS = /(?:expression\s*\(|@import|javascript:|vbscript:|data\s*:|behavior\s*:|-moz-binding)/i;
const SVG_URL_REFERENCE = /url\(\s*(?:"([^"]*)"|'([^']*)'|([^)]*))\s*\)/gi;
const IFRAME_AUTOPLAY_PARAMETERS = new Set(['autoplay', 'auto_play', 'auto-play', 'autostart', 'background']);

/**
 * Small models sometimes place Markdown link syntax inside an HTML URL
 * attribute, for example src="[YouTube](https://www.youtube.com/embed/id)".
 * Canonicalize that one malformed form before URL validation; never infer URLs
 * from ordinary text or alter a valid attribute value.
 */
export function normalizeMarkdownUrlAttribute(value: string): string {
    const trimmed = value.trim();
    const markdownLink = trimmed.match(/^\[[^\]]*\]\(\s*(https?:\/\/[^\s()]+)\s*\)$/i);
    if (markdownLink) return markdownLink[1];
    const angleWrappedUrl = trimmed.match(/^<\s*(https?:\/\/[^\s>]+)\s*>$/i);
    return angleWrappedUrl ? angleWrappedUrl[1] : trimmed;
}

/**
 * A model must never get blanket access to the local:// protocol. This permits
 * only an exact URL that the application already received from a trusted tool.
 */
export function isTrustedLocalMediaUrl(value: string, trustedUrls?: readonly string[]): boolean {
    if (!trustedUrls?.length) return false;
    try {
        const candidate = new URL(value);
        if (candidate.protocol !== 'local:') return false;
        return trustedUrls.some(trusted => {
            try {
                const allowed = new URL(trusted);
                return allowed.protocol === 'local:' && allowed.href === candidate.href;
            } catch {
                return false;
            }
        });
    } catch {
        return false;
    }
}

function isSafeUrl(
    value: string,
    element: Element,
    attribute: string,
    source: RichContentSource,
    trustedLocalMediaUrls?: readonly string[]
): boolean {
    const trimmed = value.trim();
    if (!trimmed || trimmed.startsWith('#')) return true;
    if (/^(?:\.\.?\/|\/)(?!\/)/.test(trimmed)) {
        const tag = element.tagName.toUpperCase();
        return attribute === 'src' && (tag === 'IMG' || tag === 'AUDIO' || tag === 'VIDEO' || tag === 'SOURCE');
    }

    let parsed: URL;
    try {
        parsed = new URL(trimmed, window.location.href);
    } catch {
        return false;
    }

    const protocol = parsed.protocol.toLowerCase();
    const tag = element.tagName.toUpperCase();
    if (protocol === 'http:' || protocol === 'https:') {
        if (tag === 'IFRAME') {
            if (protocol !== 'https:') return false;
            const host = parsed.hostname.toLowerCase();
            if (host === 'localhost' || host === '::1' || host.endsWith('.localhost') ||
                /^127\./.test(host) || /^10\./.test(host) || /^192\.168\./.test(host) ||
                /^169\.254\./.test(host) || /^172\.(?:1[6-9]|2\d|3[01])\./.test(host)) return false;
        }
        return true;
    }
    if (attribute === 'href' && (protocol === 'mailto:' || protocol === 'tel:')) return true;
    if (attribute === 'src' && (tag === 'IMG' || tag === 'AUDIO' || tag === 'VIDEO' || tag === 'SOURCE')) {
        if (protocol === 'blob:') return true;
        if (protocol === 'data:') {
            return /^data:(?:image|audio|video)\/[a-z0-9.+-]+(?:;[a-z0-9=.+-]+)*(?:;base64)?,/i.test(trimmed);
        }
        if ((protocol === 'file:' || protocol === 'local:') && source === 'trusted-ui') return true;
        if (protocol === 'local:' && isTrustedLocalMediaUrl(trimmed, trustedLocalMediaUrls)) return true;
    }
    return false;
}

function sanitizeStyle(element: HTMLElement): void {
    const raw = element.getAttribute('style');
    if (!raw) return;
    const probe = document.createElement('span');
    probe.setAttribute('style', raw);
    const kept: string[] = [];
    for (let index = 0; index < probe.style.length; index += 1) {
        const property = probe.style.item(index).toLowerCase();
        const value = probe.style.getPropertyValue(property).trim();
        if (!SAFE_STYLE_PROPERTIES.has(property) || DANGEROUS_CSS.test(value)) continue;
        if (property === 'position' && /^(?:fixed|sticky)$/i.test(value)) continue;
        kept.push(`${property}:${value}${probe.style.getPropertyPriority(property) ? ' !important' : ''}`);
    }
    if (kept.length) element.setAttribute('style', kept.join(';'));
    else element.removeAttribute('style');
}

/**
 * Mermaid uses url(#id) to reference local markers, masks, and gradients. These
 * references are not network requests and must survive SVG sanitization. Every
 * other url(...) target remains disallowed in generated SVG styling.
 */
export function hasUnsafeSvgStyle(value: string): boolean {
    if (DANGEROUS_SVG_CSS.test(value)) return true;
    for (const match of value.matchAll(SVG_URL_REFERENCE)) {
        const target = (match[1] ?? match[2] ?? match[3] ?? '').trim();
        if (!target.startsWith('#')) return true;
    }
    return false;
}

/** Disable background playback regardless of the media provider's query syntax. */
export function stripIframeAutoplayParameters(rawUrl: string): string {
    try {
        const url = new URL(rawUrl);
        for (const key of Array.from(url.searchParams.keys())) {
            if (IFRAME_AUTOPLAY_PARAMETERS.has(key.toLowerCase())) url.searchParams.delete(key);
        }
        return url.toString();
    } catch {
        return rawUrl;
    }
}

function hardenIframe(iframe: HTMLIFrameElement): void {
    // A srcdoc document is model-authored code and must remain on an opaque
    // origin. A remote HTTPS embed is already isolated by its own origin;
    // sandboxing it additionally can make player SDKs (notably YouTube) reset
    // their frame repeatedly in Chromium/Electron.
    const isInlineDocument = iframe.hasAttribute('srcdoc');
    if (isInlineDocument) {
        iframe.setAttribute('sandbox', 'allow-scripts allow-forms allow-popups allow-presentation');
    } else {
        // Do not remount/restrict the remote player's browsing context beyond
        // URL validation, which already permits HTTPS only and blocks private hosts.
        iframe.removeAttribute('sandbox');
    }
    iframe.setAttribute(
        'referrerpolicy',
        isInlineDocument ? 'no-referrer' : 'strict-origin-when-cross-origin'
    );
    if (!iframe.hasAttribute('loading')) iframe.setAttribute('loading', 'lazy');
    const source = iframe.getAttribute('src');
    if (source) iframe.setAttribute('src', stripIframeAutoplayParameters(source));
    iframe.removeAttribute('autoplay');
    iframe.setAttribute(
        'allow',
        'accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share; fullscreen'
    );
    iframe.setAttribute('allowfullscreen', '');
}

/** Sanitize rich visual content without flattening its layout or media. */
export function sanitizeRichContent(html: string, options: RichContentPolicyOptions = {}): string {
    if (!html) return '';
    if (typeof window === 'undefined' || typeof DOMParser === 'undefined') {
        return html.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    }

    const parsed = new DOMParser().parseFromString(html, 'text/html');
    const source = options.source || 'agent';
    for (const element of Array.from(parsed.body.querySelectorAll('*'))) {
        const tag = element.tagName.toUpperCase();
        if (REMOVE_ELEMENT_TAGS.has(tag)) {
            element.remove();
            continue;
        }
        if (UNWRAP_TAGS.has(tag)) {
            element.replaceWith(...Array.from(element.childNodes));
            continue;
        }
        for (const attr of Array.from(element.attributes)) {
            const name = attr.name.toLowerCase();
            if (name.startsWith('on') || DROP_ATTRIBUTES.has(name)) {
                element.removeAttribute(attr.name);
                continue;
            }
            if (URL_ATTRIBUTES.has(name)) {
                const normalizedUrl = normalizeMarkdownUrlAttribute(attr.value);
                if (!isSafeUrl(normalizedUrl, element, name, source, options.trustedLocalMediaUrls)) {
                    element.removeAttribute(attr.name);
                } else if (normalizedUrl !== attr.value) {
                    element.setAttribute(attr.name, normalizedUrl);
                }
            }
        }
        if (element instanceof HTMLElement) sanitizeStyle(element);
        if (element instanceof HTMLAnchorElement) element.setAttribute('rel', 'noopener noreferrer nofollow');
        if (element instanceof HTMLIFrameElement) hardenIframe(element);
    }
    return parsed.body.innerHTML;
}

export function sanitizeGeneratedSvg(svg: string): string {
    if (!svg || typeof DOMParser === 'undefined' || typeof XMLSerializer === 'undefined') return '';
    const parsed = new DOMParser().parseFromString(svg, 'image/svg+xml');
    if (parsed.querySelector('parsererror')) return '';

    // Mermaid uses foreignObject for labels and node content. It remains safe here
    // because Mermaid produced the SVG and the attribute/content pass below still
    // removes executable nodes, handlers, and unsafe URLs.
    parsed.querySelectorAll('script, iframe, object, embed').forEach(node => node.remove());
    parsed.querySelectorAll('*').forEach(element => {
        for (const attr of Array.from(element.attributes)) {
            const name = attr.name.toLowerCase();
            const value = attr.value.trim();
            if (name.startsWith('on') || DROP_ATTRIBUTES.has(name)) {
                element.removeAttribute(attr.name);
            } else if ((name === 'href' || name === 'xlink:href') && /^(?:javascript|vbscript|data):/i.test(value)) {
                element.removeAttribute(attr.name);
            } else if (name === 'style' && hasUnsafeSvgStyle(value)) {
                element.removeAttribute(attr.name);
            }
        }
    });
    parsed.querySelectorAll('style').forEach(style => {
        if (hasUnsafeSvgStyle(style.textContent || '')) style.remove();
    });
    return new XMLSerializer().serializeToString(parsed.documentElement);
}

/** Build active model HTML for an opaque-origin iframe, never the chat DOM. */
export function buildSandboxedArtifactDocument(html: string): string {
    const csp = [
        "default-src 'none'", "img-src https: http: data: blob:",
        "media-src https: http: data: blob:", "font-src https: data:",
        "style-src 'unsafe-inline' https:",
        "script-src 'unsafe-inline' 'unsafe-eval' https: http:",
        "connect-src https: http:", "frame-src https: http:",
        "form-action https:", "base-uri 'none'"
    ].join('; ');
    return `<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="${csp}"><meta name="referrer" content="no-referrer"><style>html,body{margin:0;min-height:100%;background:#090d16;color:#e5e7eb}</style></head><body>${html}</body></html>`;
}
