/**
 * Agent Chat & Conversation Utilities
 * Path: src/services/core/agent/chat.ts
 * Canonical text-channel segmentation for the agent runtime.
 */
import { MessageBlock, ToolCall, FileTarget } from '../../../types';
import { normalizeThoughtDelimiters } from '../toolTransport';

export { normalizeThoughtDelimiters } from '../toolTransport';

/**
 * Keep malformed transport visible without allowing Markdown/HTML parsing to
 * discard its custom tags. This does not change the source text semantically:
 * users see the literal protocol emitted by the model.
 */
function preserveRawToolTransportForDisplay(text: string): string {
    return text
        .replace(/<\|(?:tool_call|tool_response)(?:\|)?>/gi, match => match.replace('<', '&lt;'))
        .replace(/<\/?(?:tool_call|function_call|tool_use|tool_response)\b[^>]*>/gi, match => match.replace('<', '&lt;'));
}

/** Removes only thought delimiters; raw model output remains visible for diagnosis. */
export function cleanNativeReasoningForDisplay(text?: string): string {
    return preserveRawToolTransportForDisplay(normalizeThoughtDelimiters(text || ''))
        .replace(/<\/?thinking>/gi, '')
        .trim();
}

/**
 * Codex exposes a public summary rather than private chain-of-thought. Keep
 * adjacent Markdown emphasis spans separated so streamed summary updates do
 * not render as one visually glued phrase (for example `**Plan****Check**`).
 */
export function cleanProviderReasoningSummary(text?: string): string {
    const value = String(text || '').trim();
    if (!value) return '';

    // Insert a real separator before the Markdown renderer strips the markers
    // from the visible block. This keeps the summary faithful while fixing
    // the provider's `**Plan****Check**` output.
    return value.replace(/(\*\*[^*\r\n]+?\*\*)(?=\*\*[^*\r\n]+?\*\*)/g, '$1 ');
}

/**
 * Segments a text into thought and narrative blocks, preserving <think> content.
 */
export function segmentThoughtsAndNarrative(text: string): MessageBlock[] {
    if (!text) return [];

    // Preserve every token generated by the model. Tool-looking text remains
    // non-executable unless the isolated transport parser accepts it.
    const processingText = preserveRawToolTransportForDisplay(normalizeThoughtDelimiters(text));
    const blocks: MessageBlock[] = [];
    const thinkRegex = /<thinking>([\s\S]*?)<\/thinking>/gi;
    let lastIdx = 0;
    let match;

    while ((match = thinkRegex.exec(processingText)) !== null) {
        const preamble = processingText.substring(lastIdx, match.index);
        if (preamble.trim()) {
            const cleaned = preamble.trim();
            if (cleaned) blocks.push({ type: 'answer', content: cleaned, isFromNarrative: true });
        }

        const thoughtContent = match[1].trim();
        if (thoughtContent) blocks.push({ type: 'thought', content: thoughtContent });
        lastIdx = thinkRegex.lastIndex;
    }

    let remaining = processingText.substring(lastIdx);
    const partialMatch = remaining.match(/<thinking>([\s\S]*)$/i);
    if (partialMatch) {
        const beforePartial = remaining.substring(0, partialMatch.index);
        if (beforePartial.trim()) {
            const cleaned = beforePartial.trim();
            if (cleaned) blocks.push({ type: 'answer', content: cleaned, isFromNarrative: true });
        }

        const thoughtContent = partialMatch[1].trim();
        if (thoughtContent) blocks.push({ type: 'thought', content: thoughtContent });
        return blocks;
    }

    remaining = remaining.replace(/<\/?thinking>/gi, '').trim();
    if (remaining) {
        const cleaned = remaining.trim();
        if (cleaned) blocks.push({ type: 'answer', content: cleaned, isFromNarrative: true });
    }

    return blocks;
}

export function extractToolSnippet(toolName: string, currentFiles: any, currentTools: any): string {
    // 1. Try to find in CORE Library
    const libraryFile = Object.keys(currentFiles).find(k => k.toLowerCase().endsWith('tool_usage_library.md'));
    const libraryContent = libraryFile ? currentFiles[libraryFile] : '';

    if (libraryContent) {
        const escapedName = toolName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        const regex = new RegExp(`## \\[${escapedName}\\]\\s*\\r?\\n([\\s\\S]*?)(?=\\n##|$)`, 'i');
        const match = libraryContent.match(regex);
        if (match) return match[1].trim();
    }

    // 2. Try to find in Skill Folder (usage.md)
    const skillUsageFile = Object.keys(currentTools).find(k =>
        k.toLowerCase().includes(toolName.toLowerCase()) && k.toLowerCase().endsWith('usage.md')
    );
    if (skillUsageFile) return currentTools[skillUsageFile];

    return "";
}

export function autoExtractSources(actions: string[], history: any[], tools: any[]): string[] {
    const found: Set<string> = new Set();

    // 1. Scan for filenames (exclude internal protocol files)
    actions.forEach(a => {
        const fileMatch = a.match(/"filename"\s*:\s*"(.*?)"/i);
        if (fileMatch) {
            const fn = fileMatch[1];
            const isInternal = fn.startsWith('@CORE/') || fn.toLowerCase() === 'tasks.md' || fn.toLowerCase() === 'active_context.md';
            if (!isInternal) found.add(fn);
        }
    });

    // 2. Cross-reference actions with dynamic tool metadata
    actions.forEach(a => {
        tools.forEach(t => {
            const toolName = t.function.name;
            // Check if toolName is present in the action string (e.g. "tool_name(...)")
            const nameRegex = new RegExp(`(^|[^a-zA-Z0-9_])${toolName}([^a-zA-Z0-9_]|$)`, 'i');
            if (nameRegex.test(a)) {
                const canonical = toolName;
                if (['web_search', 'read_url'].includes(canonical)) {
                    found.add("Investigación Web");
                } else if (!['read_file', 'update_file', 'patch_file', 'delete_file', 'list_files', 'search_files', 'search_pattern'].includes(canonical)) {
                    // Use the first part of the description as the source name
                    const desc = t.function.description.split('.')[0].split('|')[0].trim();
                    found.add(`Neural Skill: ${desc || toolName}`);
                }
            }
        });
    });

    // 3. Scan for URLs in tool responses
    history.forEach(m => {
        if (m.role === 'tool' && typeof m.content === 'string' && m.content.length < 5000) {
            const urls = m.content.match(/https?:\/\/[a-z0-9.-]+\.[a-z]{2,}/gi);
            if (urls) urls.slice(0, 2).forEach(u => found.add(u));
        }
    });
    return Array.from(found);
}

export async function applyBatchTaskTicking(
    toolCalls: ToolCall[], 
    currentFiles: any, 
    currentWorkSpace: any, 
    saveFileFn: any,
    onLog: (msg: string) => void
): Promise<{ modified: boolean, turnAutoTasks: string[] }> {
    const turnAutoTasks: string[] = [];
    if (toolCalls.length === 0) return { modified: false, turnAutoTasks };
    
    const findTaskStore = () => {
        // Enforce STRICT predefined route: @CORE/tasks.md
        const keys = Object.keys(currentFiles);
        const taskKey = keys.find(k => k.toLowerCase() === 'tasks.md');
        if (taskKey) return { store: currentFiles, target: 'core' as FileTarget, key: taskKey };
        return null;
    };



    const taskInfo = findTaskStore();
    if (!taskInfo) return { modified: false, turnAutoTasks };

    const { store, target, key } = taskInfo;
    const content = store[key];
    if (!content || !content.trim()) return { modified: false, turnAutoTasks };

    let lines = content.split('\n');
    let modified = false;

    // Mapping tool names to natural language synonyms for better detection
    const toolSynonyms: Record<string, string[]> = {
        'read_file': ['leer', 'consultar', 'revisar', 'analizar', 'ver', 'read', 'check', 'inspect', 'view', '读取', '阅读', '查看', '浏览'],
        'update_file': ['escribir', 'crear', 'guardar', 'modificar', 'actualizar', 'generar', 'write', 'create', 'save', 'update', 'generate', 'make', '写', '写入', '编写', '创建', '保存', '更新'],
        'patch_file': ['parchear', 'aplicar', 'arreglar', 'corregir', 'editar', 'patch', 'apply', 'fix', 'correct', 'edit', 'refactor', '修补', '应用', '修复', '编辑'],
        'list_files': ['listar', 'explorar', 'ver archivos', 'inspeccionar', 'list', 'explore', 'ls', 'dir', 'browse', '列出', '表', '浏览', '目录'],
        'search_files': ['buscar archivo', 'encontrar archivo', 'localizar archivo', 'filename', 'file name', 'find file', 'locate file', 'buscar fichero', '查找文件'],
        'search_pattern': ['buscar en el contenido', 'buscar texto', 'patrón', 'regex', 'grep', 'search content', 'find in files', 'content search', '搜索内容', '查找文本'],
        'web_search': ['investigar', 'noticias', 'google', 'buscar en internet', 'deep_research', 'research', 'search web', 'look up', '搜网', '网络搜索', '搜索网页'],
        'web_search_more': ['más resultados', 'mas resultados', 'siguiente página', 'siguiente pagina', 'buscar más', 'buscar mas', 'more results', 'next results', 'next page', '继续搜索', '更多结果'],
        'deep_research': ['investigar', 'noticias', 'google', 'buscar en internet', 'web_search', 'research', 'deep research', '深度搜索', '深入搜索', '深入探查'],
        'run_console': ['ejecutar', 'comando', 'terminal', 'consola', 'git', 'run', 'execute', 'command', 'terminal', 'console', 'npm', 'node', 'python', '运行', '执行', '命令'],
        'get_system_metrics': ['métricas', 'cpu', 'ram', 'estado del sistema', 'salud', 'metrics', 'status', 'health', 'system info', '系统指标', '状态', '健康度'],
        'list_available_skills': ['habilidades', 'skills', 'capacidades', 'funciones extra', 'list skills', 'show abilities', '列表技能', '展示能力', '技能列表'],
        'miku_clock': ['hora', 'reloj', 'tiempo', 'quién eres', 'time', 'clock', 'greet', '时间', '小时', '问候', '打招呼'],
        'get_crypto_price': ['bitcoin', 'crypto', 'precio', 'cripto', 'cotización', 'moneda', 'price', 'coin', 'market', '比特币', '加密货币', '价格', '行情', '汇率'],
        'delete_file': ['borrar', 'eliminar', 'quitar', 'limpiar', 'suprimir', 'delete', 'remove', 'rm', 'clear', 'erase', '删除', '移除', '清理', '清除'],
    };

    const normalizeForMatch = (s: string) => {
        return s.toLowerCase()
            .replace(/@(?:CORE|WORKSPACE|TOOLS|LIBRARY|EXTRA|ROOT)\//gi, '') // Strip common prefixes
            .replace(/\.[a-z0-9]+$/i, '') // Strip extensions for fuzzy matching
            .trim();
    };

    for (const toolCall of toolCalls) {
        const toolName = toolCall.function.name;
        const args = toolCall.function.arguments || {};
        // Expanded mainArg detection to include text (for final_answer) and item/query variations
        const mainRaw = (args.filename || args.query || args.topic || args.url || args.command || args.path || args.text || args.item || '').toString();
        const mainArgClean = normalizeForMatch(mainRaw);
        
        let markedInThisPass = false;
        lines = lines.map(line => {
            // Skip already checked lines or headers
            if (markedInThisPass || !line.trim().startsWith('- [ ]')) return line;

            const lowerLine = line.toLowerCase();
            const lowerTool = toolName.toLowerCase();
            const cleanLine = normalizeForMatch(line.replace('- [ ]', ''));
            
            // FUZZY MATCHING POLICY:
            // 1. Direct name match (e.g., "- [ ] @web_search")
            const directMatch = lowerLine.includes(lowerTool) || lowerLine.includes(`@${lowerTool}`);
            
            // 2. Synonym match
            const hasSynonym = (toolSynonyms[lowerTool] || []).some(s => lowerLine.includes(s.toLowerCase()));
            const toolMatch = directMatch || hasSynonym;
            
            // 3. Keyword Overlap Match (Improved logic)
            // We split both the task line and the tool argument into tokens to find significant shared concepts
            const getKeywords = (str: string) => str.toLowerCase().split(/[^a-zA-Z0-9áéíóúñ]+/i).filter(w => w.length >= 4);
            const lineKeywords = getKeywords(cleanLine);
            const argKeywords = getKeywords(mainArgClean);
            
            const hasSignificantOverlap = argKeywords.some(kw => lineKeywords.includes(kw));
            const subStringMatch = mainArgClean.length > 3 && (cleanLine.includes(mainArgClean) || mainArgClean.includes(cleanLine));
            
            const argMatch = mainArgClean === "" || hasSignificantOverlap || subStringMatch;
            
            // Exclude meta-updates to tasks.md itself
            if (lowerTool === 'update_file' || lowerTool === 'patch_file') {
                if (mainArgClean.includes('tasks')) return line;
            }

            // COHERENCE POLICY: Match if tool concept matches target concept
            if (toolMatch && argMatch) {
                modified = true;
                markedInThisPass = true;
                const taskName = line.replace('- [ ]', '').trim();
                if (!turnAutoTasks.includes(taskName)) turnAutoTasks.push(taskName);
                return line.replace('- [ ]', '- [x]');
            }
            return line;
        });
    }

    if (modified) {
        const newContent = lines.join('\n').trim();
        await saveFileFn(key, newContent, target);
        store[key] = newContent;
    }
    
    return { modified, turnAutoTasks };
}

export function getActionFingerprint(toolName: string, args: Record<string, any>): string {
    if (!toolName) return 'unknown_action';
    try {
        const safeArgs = args || {};
        const sortedArgs = Object.keys(safeArgs).sort().reduce((acc, key) => {
            acc[key] = safeArgs[key];
            return acc;
        }, {} as Record<string, any>);
        return `${toolName}|${JSON.stringify(sortedArgs)}`;
    } catch (err) {
        return `${toolName}|error_fingerprint`;
    }
}
